### ISSUE TITLE
Negative feedback internal server error

### ISSUE THREAD

**Issue by ChromaticPanic** [ai-cfia/nachet-datastore#47]
Server response
```html
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

Payload
```json
{
  "userId":"a427278e-28df-428f-8937-ddeeef44e72f",
  "inferenceId":"1fd131c8-6cac-4c3b-badf-3c2c20a516c3",
  "boxes":[
      {
        "classId":"d8e0adb6-91c5-4fec-8c3c-6b49fe9a50ab",
        "label":"Brassica juncea","boxId":"3fc8ddb6-61d1-4bdb-a9de-173b5de38c2d",
        "box": {
                "topX":255,
                "topY":112,
                "bottomX":687,
                "bottomY":410
             },
        "comment":"Wrong Seed"
       }
    ]
}
```

Method datastore.new_annoted_inference_feeback(cursor, inference_id, user_id, boxes)

```
[2024-06-21 13:32:35,366] ERROR in app: Exception on request POST /feedback-negative
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/quart/app.py", line 1403, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/quart/app.py", line 1441, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/quart/app.py", line 1029, in handle_user_exception
    raise error
  File "/home/vscode/.local/lib/python3.11/site-packages/quart/app.py", line 1439, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/quart/app.py", line 1535, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nachet-backend/app.py", line 539, in feedback_negative
    await datastore.save_annoted_feedback(cursor, inference_id, user_id, boxes)
  File "/workspaces/nachet-backend/storage/datastore_storage_api.py", line 127, in save_annoted_feedback
    await datastore.new_annoted_inference_feeback(cursor, inference_id, user_id, boxes)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'datastore' has no attribute 'new_annoted_inference_feeback'
```

**Comment by ChromaticPanic** [comment]
Looks like it's because the new methods are not on main yet

**Comment by Francois-Werbrouck** [comment]
@ChromaticPanic This should soon be fixed by a merge in the backend. 

```
  File "/workspaces/nachet-backend/storage/datastore_storage_api.py", line 127, in save_annoted_feedback
    await datastore.new_annoted_inference_feeback(cursor, inference_id, user_id, boxes)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
It also isn't a datastore issue since those return specific error type to identify them.

**Comment by ChromaticPanic** [comment]
Fixed in https://github.com/ai-cfia/nachet-backend/pull/93
